name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
    
  swiftwasm_deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
      - uses: swiftwasm/swiftwasm-action@v5.8
        with:
          shell-action: carton bundle
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./Bundle

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Bundle
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    needs: swiftwasm_deploy
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2          

          

  
