name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  swiftwasm_deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: swiftwasm/swiftwasm-action@v5.8
        with:
          shell-action: carton bundle
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          publish_dir: ./Bundle
          
  
